### ISSUE TITLE
[REQ/FIX] "MovieFPS" controls speed as well

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#101]
-Lykon & I are working on upgrading FMVs to 30fps.
-There are 2 types of vids: FMV, causes no glitch when upgrading, and MBG, where code change is needed if we upgrade to 30fps, we're still figuring that out.
-when "MovieFPS = 15", it's the same as vanilla: FMV and MBG are capped to 15fps. A 30fps video will play at normal speed at 15fps.
-when "MovieFPS =30", FMVs of 30fps are sped up to twice the speed (audio is still constant). The only workaround we have is put "MovieFPS =30" and change the FMV to 15fps 1/2 the speed.

What would help tremendously:
1) that "MovieFPS = 30" plays 30fps videos at 30fps normal speed so we don't depend on Memoria to have functional videos (If we apply our workaround, uninstalling Memoria would make the videos slowmotion)
2) to have 2 separate options for MBG fps and FMV fps. MBG videos can't be as easily upgraded.

**Comment by Kidel** [comment]
I'm the Lykon guy he's talking about. 

Allow me to add something. Fixing this ...

> that "MovieFPS = 30" plays 30fps videos at 30fps normal speed so we don't depend on Memoria to have functional videos (If we apply our workaround, uninstalling Memoria would make the videos slowmotion)

... may also fix the fact that 30 fps MBG videos go out of sync with characters because of the starting animation frame. 

Characters move after a certain frame, but the engine skips frames to achieve 15fps if the MBG video provided is 30fps. This may be why characters go out of sync. 

The way we fixed some MBG sync was using Hades to change this code: 
![image](https://user-images.githubusercontent.com/3390842/82131615-49320880-97d7-11ea-9d14-3ef692d572f3.png)

This may not be required however if the engine plays the MBG correctly at 30fps. It's just a theory and a way to say that the FMV issue should have priority. 


Also having a native 30fps MBG and a character animated at 15 fps may look like crap, so we should also take that into account.

**Comment by Albeoris** [comment]
Hi guys! I need examples on which I can see what is working incorrectly and how it should work.

**Comment by Albeoris** [comment]
I think the problem is here somewhere.

```
		public Int32 TotalFrame
		{
			get
			{
				return (Int32)(this.currentFPS * (Double)this.Duration);
			}
		}
```

**Comment by Albeoris** [comment]
```
                        flag |= this.isFMV;
                        if (flag)
                        {
                            if (this.preciseTimeCycleCounter == 0)
                            {
                                this.m_elapsedTime += 0.066 * (double)this.playSpeed;
                            }
                            else
                            {
                                this.m_elapsedTime += 0.067 * (double)this.playSpeed;
                            }
```

One more place.

**Comment by Albeoris** [comment]
I found [sources ](https://github.com/Albeoris/MobileMovieTexture/blob/master/MMTPlugin/theorawrapper/theorawrapper.cpp) of the native plugin.

**Comment by Kidel** [comment]
For reference here are the metadata of the *original* videos: 
![image](https://user-images.githubusercontent.com/3390842/82141598-3e0ec500-9837-11ea-9f29-2d1af40e1917.png)

And this is after we've worked on them:
![image](https://user-images.githubusercontent.com/3390842/82141603-45ce6980-9837-11ea-8cac-0845dccb9f41.png)

I don't think we have a codec problem, it's probably how the decoder in FF9 steam/android is configured, so what you found may be right on spot. What's funny is that apparently (I din't check myself) @snouz was able to get a correct frame pacing by using the 30fps option in memoria (just a faster video). However I'd probably need proof for that if possible, so that we 100% know that it's not simply playing faster but still 15 fps. 

You can find them all here
https://mega.nz/folder/cVchlAbL
this is the password: A5qU-wvZiy3wc2Mm_bGeag

**Comment by Albeoris** [comment]
Done.
The option MovieFPS is removed from the configuration. Now the game itself determines the FPS.
![](https://i.imgur.com/r84woeK.png)
![](https://i.imgur.com/JMVu3qU.jpg)

**Comment by Kidel** [comment]
That's great! 

What about MBGs? 30fps MBG movies also had the problem that character animations started at the wrong frame because of the frame counter that didn't take fps into account.

**Comment by Kidel** [comment]
That's great, good job. 

What about MBGs? 30fps MBG movies also had the problem that character animations started at the wrong frame because of the frame counter that didn't take fps into account.

I've uploaded a 30fps MBG112 in that folder for testing
