### ISSUE TITLE
[v2020.08.07] PhisicalEvade use PhisicalDefence value.

### ISSUE THREAD

**Issue by DV666** [Albeoris/Memoria#151]
**Memoria version :** v2020.08.07 (last)

Hello team,

Found another issue... sorry ^^' I just test my boss with 0 evade and... still evade ôO.

After few research, i found inconsistency on PhisicalEvade get value : it use PhisicalDefence instead !

Located on Memoria/BattleUnit.

```
// Memoria.BattleUnit
// Token: 0x170004D7 RID: 1239
// (get) Token: 0x0600273A RID: 10042 RVA: 0x001F38B9 File Offset: 0x001F1AB9
// (set) Token: 0x0600273B RID: 10043 RVA: 0x001F38DE File Offset: 0x001F1ADE
public byte PhisicalEvade
{
	get
	{
		return this.Data.defence.PhisicalDefence; <=== Incorrect Data value
	}
	set
	{
		this.Data.defence.PhisicalEvade = value;
	}
}
```

**Comment by Tirlititi** [comment]
... I remember that bug well and I fixed it for the commit 8c4594c06ac2056fe065f8be51d0c1c10da589ff
For some reason, the fix wasn't taken into account in the commit.
It's the second time that happens to me. It might be that the back row bug #148 is in the same situation... I'll have to check the file's history because it didn't bug when I tested it.

Thanks for warning.
