### ISSUE TITLE
Error during Mod installation

### ISSUE THREAD

**Issue by TobiasEl** [Albeoris/Memoria#158]
Hi, I have the current error after installing Moguri Mod. This happen when I click "PLAY". Someone can help me?
![imagen](https://user-images.githubusercontent.com/36697892/106389359-2dad7300-63e3-11eb-83c8-24d66383dbf6.png)
It says "Win32Excetion". My pc is x64, I don't know if that means something

**Comment by Zer0Ph34r** [comment]
I can't give you an exact answer, but I can tell you that the Moguri Mod and the Memoria Mods aren't compatible.  Here's  a thread that explains some of the details: https://steamcommunity.com/groups/ff-modding/discussions/13/1636410430566848530/

If you are trying to switch between mods (you used Memoria and want to use Moguri now) then the easiest fix is to uninstall your game, delete all lingering files (except the save files), then re-install and then attempt to use the Moguri Mod.
The issue you're running into right now is that both the Memoria Mod and the Moguri Mod Guis are trying to run at the same time and are running into each other

**Comment by Albeoris** [comment]
> I can tell you that the Moguri Mod and the Memoria Mods aren't compatible.

Moguri Mod and the Memoria Mod are fully compatible. All Moguri changes are included in the Memoria.

**Comment by Albeoris** [comment]
The executable file was not found. 

1. Uncheck "Debuggable" in the launcher. This will help if there is no Debugger directory in the game folder. 
2. Make sure that the game folder contains both x64 and x86 directories. If any of them are missing, make sure that you are not trying to run an incompatible version (X64 checkbox).

**Comment by TobiasEl** [comment]
Hi. All that is correct: x86 and x64 folders are in the game directory
![imagen](https://user-images.githubusercontent.com/36697892/106448627-538a5480-6483-11eb-9b48-328bb3da3357.png)
And I unchek debugger. The error is the same. In fact if I check debugger the error message is smaller:
![imagen](https://user-images.githubusercontent.com/36697892/106449033-d6131400-6483-11eb-95b7-2f9a10d090df.png)

**Comment by TobiasEl** [comment]
It says that ".\x64\FF9.exe" don't found. But here it is:
![imagen](https://user-images.githubusercontent.com/36697892/106449365-30ac7000-6484-11eb-82b4-2276bffd03a8.png)

**Comment by Albeoris** [comment]
Most likely, reinstalling the game and the mod will help you.

But we can reflect on how this happened.
See, the game uses a relative path: .\X64\ff9.exe
Thus, the OS resolves it relative to the working directory FF9Launcher.exe

If you launched Launcher manually or from Steam, it should point to the game folder.
But if you launch the game through a shortcut, it may indicate a different working directory.

If you have previously installed FF9 in a different location, you may have saved registry entries for the old directory.

If you manually transferred the game folder, this may also be the reason.

Also, the problem may be that the game and the launcher were installed from different users, and the current user does not have access rights to the executable file.

Any thoughts on this?

I will correct the code (Memoria) so that in the future it will display the full path to the file, and not the relative one.

**Comment by TobiasEl** [comment]
The first time I run the game (before installing the Mod) was as admin. Maybe that is the reason?

**Comment by Albeoris** [comment]
@TobiasEl , has the problem been solved in the latest version of the mod?

**Comment by kamikazilucas** [comment]
i still have this problem and im on latest version

**Comment by Albeoris** [comment]
> i still have this problem and im on latest version

Hi, share the error message / screenshot.
