### ISSUE TITLE
cannot escape from any battle

### ISSUE THREAD

**Issue by Ramonlaw** [Albeoris/Memoria#204]
when I press the keys to flee, an animation is made but it stays in an infinite attempt and meanwhile the enemies continue to attack me but I can't escape... which leaves me as the only alternative to use zidane flee's active ability

I've already tried several things like changing the combat style to active or wait both with the launcher's "turn-based battles" checked or unchecked and I can't escape from combat under any circumstances

**Comment by Ramonlaw** [comment]
I can't escape battles by using key combination so characters start running but I can never successfully escape no matter what mode I'm playing

the only way i found to escape the battles is by using zidane's active flee ability

**Comment by Albeoris** [comment]
Share Memoria.log and output_log.txt please.

**Comment by Ramonlaw** [comment]
[Memoria.log](https://github.com/Albeoris/Memoria/files/9163170/Memoria.log)
[output_log.txt](https://github.com/Albeoris/Memoria/files/9163173/output_log.txt)

**Comment by Ramonlaw** [comment]
any update? I'm streaming on twitch and I'm so sad that I can't escape the battles

**Comment by Tirlititi** [comment]
I didn't see anything that would report a problem with flee in your logs.

I think that you are only unlucky when trying to flee. The chances of fleeing depends on the difference between your party's level and the enemies' level. Also, remember that you can never flee while the ATB is paused (when you are in menus in ATB wait mode) or while any enemy is attacking.
If you face 2 enemies or more, it can be very easy to try to flee for hours with no chance of success because the enemies just keep taking turns alternately.

**Comment by barkermn01** [comment]
I think @Tirlititi is right this is not a bug, it's a deliberate mechanic of the game to try and stop people from getting too far ahead in the story versus their level, the aim of that mechanic is to prevent players from getting stuck where they can't kill trash mobs to level up and they can't get past an event locking them into an area so it would kill a run though.
