### ISSUE TITLE
Trance doesn't activate if you have 0 MP (autotrance mode OFF)

### ISSUE THREAD

**Issue by Gianluca90** [Albeoris/Memoria#211]
With "NoAutoTrance = 1" , if you try to enter Trance and you don't have MP, the command will fail, and the field text will say "Not enough MP" . 
Moreover, every time you want to enter Trance, before the "Trance" field message appear, there is a field message saying "Vanish" , and you consume 8 MP to enter trance.
Since the Spell "Vanish" cost exactly 8 MP, it seems thet the game cast "Vanish" when you enter Trance, so that would explain why you can't enter Trance with 0 MP.

This issue is present with "NoAutoTrance = 1" ; with "NoAutoTrance = 0" , Trance worked without using any MP, although in this last case, with character that enters battle with Trance bar full, i needed to get hit by the enemy before Trance kicked in.

EDIT: i also noted that, with "NoAutoTrance = 1" , every time you enter Trance, the character change is row; when his turn is up, he returns to his original row, but if in the meantime an enemy attack him, he takes damage as if he is in the "new" row.

Lmk if you need other informations.

**Comment by Tirlititi** [comment]
Thanks a bunch for reporting this issue.
I fixed it in the commit 51c20d7

The behaviour "a character that enters battle with Trance bar full needs to get hit by the enemy before Trance kicked in" seems rather OK to me. That situation normally never happens, except when toggling on/off the ``NoAutoTrance`` option. Even then, I think it's better to require a hit instead of triggering the trance on the battle start.
