### ISSUE TITLE
[request] add the version of the patcher somewhere in the UI

### ISSUE THREAD

**Issue by mer2329** [Albeoris/Memoria#251]
this would make bug reporting much easier.

**Comment by mer2329** [comment]
i dont see any title bar in the main UI nor in the mod manager UI...
![image](https://github.com/Albeoris/Memoria/assets/6768243/89bfeb9f-dbb2-4f0f-860e-75ea4e2a358b)

**Comment by Tirlititi** [comment]
Hm, that's because you don't have the latest release.
Maybe it's my fault because I didn't update the link to the latest release properly in a couple of forum threads until very recently.
![MemoriaLatestRelease](https://github.com/Albeoris/Memoria/assets/20627826/fec63dea-6c53-454e-92d1-6c81193a79a0)

**Comment by mer2329** [comment]
i grab it from github, but i didnt see it in the new version, didnt check though, ill double check now
