### ISSUE TITLE
The sound isn't being configured -  Memoria v2023.06.11

### ISSUE THREAD

**Issue by Felipefpl** [Albeoris/Memoria#294]
I installed moguri 8.3 and the the latest memoria as requested and i adjusted the sound configurations to my liking but it didnt work, it seems to affect only the cutscenes. Even so there is another problem:

The sound of the cutscenes is lower than the sound in-game, ideally both should have the same volume. I can reduce the sound fx/music in-game only when i change the volume in the Sound - Control Panel on windows.

I have win10, realtek 887 ALC sound card and 15 GB RAM in case you need to know the specs.

**Comment by snouz** [comment]
Ok I don't reproduce the issue, but there were some changes there since the latest release version, so there might have been a fix in the recent patch I pushed (very likely even)

Could you test this version of FF9_Launcher.exe (just replace it in the main folder) and report back if it works better? If not, could you share the content of memoria.ini? (in the same folder)

https://drive.google.com/file/d/1p7kqHue6Tt8X1xeCvWtoMnoAZ5Xp7aVr/view?usp=sharing

Thanks!

**Comment by snouz** [comment]
Thanks for the test!
You can either post it here, create a new issue, or contact me through discord, where I have the same name

**Comment by snouz** [comment]
>1 - The health warning about epilepsy seen in the beginning is displayed too fast. No idea if this is a vanilla' problem or not.
Do you have the "skip intros to menu" enabled?

>2 - The setting "Skip battle swirl" cant be disabled.
I think that's probably related to this: https://github.com/Albeoris/Memoria/issues/298, I'm working on this problem.

>3 - Several settings dont have tooltips with information attached to them.
good, point, I'll work on that!

>4 - I selected the Blue GUI but it cant be properly or fully seen when i load the game, i have 2 pics to show it.
That's not a bug, the standard is grey and the option to choose is save specific. The save will be the color you set the setting IN that save, so here's what it looks like when I changed to blue and saved to slot 8 File02:
![image](https://github.com/Albeoris/Memoria/assets/9964576/d79ff5d9-ad31-4d81-8650-9ee8abe8af09)

>5 - Several characters in-game take some time to attach during battles. This seems to happen with Zidane most of time.
I've opened a bug https://github.com/Albeoris/Memoria/issues/300, did you only have moguri installed before, or did you install memoria's latest release from june?

**Comment by snouz** [comment]
I missed that last point, 

>8 - The cutscene where kuja appears for the 1st time has the music volume too low which makes no sense since the volume is set to 100 and the music in-game runs fine (it's set to 20 due to my volume of the speakers on control panel).

What's you sound settings overall? And what moment has the music too low? Is it the rain scene where we lose against beatrix in burmecia? Isn't that an FMV? I ask because fmv is a different setting

**Comment by snouz** [comment]
I've added your comments to the tickets about the sound. Since your sound is at 30%, that's probably a case of a sound or two not being referenced by the volume control or something. I've transferred all sound related tickets to some devs who are currently reworking the sound system.

For the setting, it should be fixed in the next version, I've pushed some commits already that should avoid this problem for future people. As for putting a combo box instead of a checkbox, I prefer keeping the settings in the launcher streamlined, it's much simpler to have an on/off setting, and if someone wants to be more precise, they can edit memoria.ini. That's why you don't have EVERY settings there, just the relevant ones for casual players.

**Comment by barkermn01** [comment]
I will just update me and @SamsamTS  are working on something that should resolve much of these audio issues.

**Comment by SamsamTS** [comment]
I do believe I have fixed that bug in https://github.com/Albeoris/Memoria/pull/256
Could not reproduce with recently compiled memoria.

**Comment by snouz** [comment]
Thanks, I created a new ticket. It's probably not related to Moguri, probably a bug that can be fixed in the script of this specific character
https://github.com/Albeoris/Memoria/issues/332

**Comment by snouz** [comment]
Ah it's an old bug that I thought was fixed, found it again the other day and forgot to reactivate the ticket.
What resolution are you using?

**Comment by snouz** [comment]
> 2 - In the ending the lines spoken by Marcus close to the last cutscene are displayed too quickly to read unlike before where we could go to the next line clicking in the Ok/action button.

I opened https://github.com/Albeoris/Memoria/issues/337

> 3 - There are phrases over other phrases in the ending:

I opened https://github.com/Albeoris/Memoria/issues/338

> 4 - (I should have reported this one earlier) From the little i remember from final fantasy 9 on psx when you used a tent you recovered all HP/MP, this doesn't happen here so i deduce my memory is betraying/deceiving me or maybe it's a bug or the PC version is just different.

It's full HP if you use it in battle, half if you use it on map https://finalfantasy.fandom.com/wiki/Tent_(Final_Fantasy_IX)

Thank you for all your reports, it really helps, especially right now that there's momentum by several people to remove as many bugs as possible
