### ISSUE TITLE
Marcus not learning Skills

### ISSUE THREAD

**Issue by cass46** [Albeoris/Memoria#314]
Hi, when i use the Alt + F2 to put Marcus in the party, he doesn't learn any skills (using HadesWorkShop i found out the Memoria is giving me the Marcus 18, this one can't learn skills (is the one from the Theater that has the SFX command), i would like you to fix that or teach me how to do it, that is to put the Marcus from the 10 or 11 slots, the one that can learn skills (Blank and Cinna already are working perfecly).

**Comment by snouz** [comment]
@Tirlititi

**Comment by Tirlititi** [comment]
Is that because you used Marcus between "Start of Evil forest" and "Black Waltz 3.2 battle"?
Marcus is configured to use the SFX command set for that period.

If you want him to use another set, add a ``SetCharacterData`` line in a field script somewhere to re-configure his ability set and command set.

**Comment by cass46** [comment]
Yes, i'm just outside from the Evil Forest, thanks, i think i can hold off until disc 2 to use him (since i don't know how to add a SetCharacterData line in a field script somewhere)
