### ISSUE TITLE
Better support Linux/Steam Deck (QoL, documentation)

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#319]
Opening this issue to centralize resources and find potential improvements/bugfixes for linux and steam deck.

https://gist.github.com/Eoin-ONeill-Yokai/5016e28506071165578eb8c181700b0f

**Comment by snouz** [comment]
![image](https://github.com/Albeoris/Memoria/assets/9964576/a4207125-2017-4e1e-ab60-85935c82f825)

**Comment by Tirlititi** [comment]
For the record, [Faospark](https://steamcommunity.com/sharedfiles/filedetails/?id=2874210888), [Sonicbrawler](https://www.reddit.com/r/FinalFantasyIX/comments/xbnume/60_fps_ffix_but_its_on_steam_deck/) (in the comments) and [Admiral Buttloaf](https://steamcommunity.com/sharedfiles/filedetails/?id=3068861646) made tutorials for the installation of Memoria. Some parts may be outdated (or will be soon) because of updates of Proton, Moguri... but that's still great documentations.
