### ISSUE TITLE
Characters disappear when too far in WS (alexandria map 103 main plaza)

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#325]
![image](https://github.com/Albeoris/Memoria/assets/9964576/c3ecfb67-5a2a-4c9b-a92b-c328b2d7ebf0)

**Comment by Tirlititi** [comment]
For the record, this optimisation process that served the PSX version in order to keep the number of rendered objects relatively low at any time is coded in the field's script. It's not something automatised for all the fields but a system that appears in a couple of specific fields. For instance, you can find code like that in that field:
```
Function Alexandrian_GirlB_Loop
    while ( 1 ) {
        SetObjectFlags( 5 ) // Show the 3D model
        if ( GetEntryPosX(250) > -600 ) { // If the player character is at the right of the screen
            SetObjectFlags( 14 ) // Hide the 3D model
        }
        RunAnimation( 973 ) // Rope_L_1
        SetAnimationInOut( VAR_GlobInt16_37 / 8, VAR_GlobInt16_37 / 8 )
        Wait( 1 )
    }
    Wait( 1 )
    loop
```
