### ISSUE TITLE
Cutscene in Evil Forest: Steiner infinitely spinning

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#345]
Based on https://github.com/Albeoris/Memoria/issues/340 by @dajoma09 to separate issues

"Steiner is just infinite spinning on an Evil Forest cutscene:
![image](https://github.com/Albeoris/Memoria/assets/9964576/0268fe3b-3df6-46f8-88c3-4c64eba538ee)

I tried changing tile size, fps, turning wide screen, but i don't really know much of these things. The only thing i can think of is deleting everything and going past it on vanilla, then installing and configuring the whole mod again.

For context i'm using both Moguri and Memoria mods, plus High-res Chocographs, Playstation Sounds and Psx buttons (all three available through Memoria) plus Excalibur no time limit mod."

**Comment by snouz** [comment]
I have no idea if I can reproduce that bug, but I think Excalibur No Time Limit Mod, if it's this one: https://www.nexusmods.com/finalfantasy9/mods/50 replaces AssemblyCSharp.dll, which is the core of Memoria. I think it's based on Memoria, but not sure about this. Maybe that's the reason, or maybe it's something else that was botched, no idea. I've never heard of this bug before, even though it sounds very game breaking, so I don't know if it's reproducible.

For Excalibur no time limit mod, when we release the next version, this feature will be included (it's committed already), so it will be a simple line in Memoria.ini to change.

**Comment by Rocket-Lawnchair** [comment]
@snouz  

The issue seems to have something to do with the PSXEncounterMethod being set to 1 in Memoria.ini. I had this same problem, but when I turned that option to 0, it stopped. I also noticed that the scene seems to be slightly different when PSXEncounterMethod is set to 1 - Steiner goes a step further down the stairs, does a 180 turn for a split second before 180 again, like there's a small error in the scene, but only when PSXEncounterMethod is set to 1. I'm only using Moguri from the mods the oher user mentioned, so it's possible that also has something to do with it?

**Comment by snouz** [comment]
Thanks @Rocket-Lawnchair, I could reproduce exactly what you're talking about, and found the incriminated bit of code, I'm trying a fix.

**Comment by snouz** [comment]
The bug was also affecting several other scenes, like jumping on the platform at the entrance of Dali's cave. I've added the fix to my current pull request.

**Comment by dajoma09** [comment]
@Rocket-Lawnchair i changed PSXEncounterMethod back to 0 as you said and it worked! Ig if i find another one i'll do the same thing, tysm!
