### ISSUE TITLE
Transparency of foreground pixels ignored by 3D objects

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#352]
![image](https://github.com/Albeoris/Memoria/assets/9964576/6298b0be-d49a-48a8-b6bc-7f50702d13c0)

Background alpha is working correctly between background layers (so I can have soft edges between foreground and scrolling sky for example) but if a layer is on top of a 3D object, it will appear as alpha 1 or 0, never in between.

In the same way anti-aliasing turned out to be an easy feature, maybe this is fixable as well?

**Comment by snouz** [comment]
A good example here

![image](https://github.com/Albeoris/Memoria/assets/9964576/4716431f-2df7-4764-970c-3e3bc39440fa)

Alpha on the jar is partially transparent, showing parts of the layer under, but never a 3D object.
If someone is knowledgeable in shaders...

**Comment by snouz** [comment]
@SamsamTS, Tsuna mentioned that you might know some things about this? This has been itching me since I began working on the mod.

**Comment by julianxhokaxhiu** [comment]
Hey @snouz Tsuna brought me here. I don't have direct experience with Unity shaders but I might try to help you on the general concept. But before doing that, would you be so kind pointing me where can I find the shader code ( if any around ) and where the shader logic is applied for those specific cases? Thanks :)

**Comment by SamsamTS** [comment]
@julianxhokaxhiu There is this https://github.com/Albeoris/Memoria/tree/main/Memoria.Patcher/StreamingAssets/Shaders
Unsure if it's of any help.

**Comment by Tirlititi** [comment]
The shaders used for field objects are mainly:
- [PSX/FieldMapActor](https://github.com/Albeoris/Memoria/blob/main/Memoria.Patcher/StreamingAssets/Shaders/PSX/FieldMapActor.txt) for the 3D models of the characters,
- [PSX/FieldMap_Abr_None](https://github.com/Albeoris/Memoria/blob/main/Memoria.Patcher/StreamingAssets/Shaders/PSX/FieldMap_Abr_None.txt) for the backgrounds (there are also other ``Abr`` shaders used, in particular the ``FieldMap_Abr_1`` for most semi-transparent background layers, like lights, but I think ``Abr_None`` is what is involved in all those problems anyway as it originally wasn't meant to handle gradual transparency at all).

Also, it might help to look at my C# code in [FieldCreatorScene](https://github.com/Albeoris/Memoria/blob/main/Assembly-CSharp/Memoria/Assets/FieldCreator/FieldCreatorScene.cs#L729) because it's a relatively compact class that handles the rendering of the fields, with much fewer subtleties than the usual in-game machinery.
In particular, it setups the parameters ``_OffsetX``, ``_OffsetY``, ``_MatrixRT`` etc. that are used in the shader's code.

**Comment by snouz** [comment]
Here are saves for the whole game:
[SavedData_ww.zip](https://github.com/Albeoris/Memoria/files/15028838/SavedData_ww.zip)
You can see this happening all through the game, here's the same example from vanilla:
![image](https://github.com/Albeoris/Memoria/assets/9964576/d74f027c-4f33-4d82-8004-862fd88ba37a)
You can see it happening, because instread of having pixels from the model, we have pixels from the underlayer in green
In fact you can even see the scrolling:
![image](https://github.com/Albeoris/Memoria/assets/9964576/a714640c-8d6f-4f23-aee9-2ab3c9553212)
![image](https://github.com/Albeoris/Memoria/assets/9964576/f257a5f9-accb-4212-b499-4d2f44f3dab3)
And since there are no grey alpha pixels in vanilla, this is actually a result of the smoothing between black and white alpha pixels that become grey at the display level.

**Comment by julianxhokaxhiu** [comment]
Thanks a lot @snouz I'll investigate and come back to you

**Comment by julianxhokaxhiu** [comment]
So I did try to start looking into this, thank you very much for the save game. Have you got experience using RenderDoc on top of FF9? I did try and so far I'm not able to make it work, it seems to not detected the rendering API somehow. I wanted to start from there as it's amazing way to look at what the GPU is doing.

I did try with the vanilla installation, but let me know. I'll try also with Memoria just in case, but this is where I am so far. I'll keep you posted.

**Comment by EricHu33** [comment]
![image](https://github.com/Albeoris/Memoria/assets/13420668/0344df4c-4264-4e8d-8c36-ef742688651e)
I notice some transparent flickering during waking in front of the transparent jar.
So I assume it's because that both character and jar are in same transparent order and the renderer cannot judge which is in front and which one is behind. 

By offsetting render queue of the abr_none shader we can has correct transparent effect.
![image](https://github.com/Albeoris/Memoria/assets/13420668/72844a23-fcc2-46b0-ac97-d53d88f58d90)

however if i remember correctly the jar was not a transparent object in the original game lol.

**Comment by EricHu33** [comment]
![image](https://github.com/Albeoris/Memoria/assets/13420668/da7e605d-f0e1-430c-933d-e34f20a4d095)
The jar's render queue is **transparent**(defined in abr_none shader), while the character is **transparent+1**
![image](https://github.com/Albeoris/Memoria/assets/13420668/e7cecbbe-d4ac-4f87-bf91-5e1f5c351459)

Modifed the queue to transparent+2 will make the transparency work. but probably not intended by default. 
Since abr_none are supposed to be the background layer. I guess.

IIRC, the jar itself is not transparent in original game, anyway, at least this provide an option to workaround it.

**Comment by snouz** [comment]
Holy shit that works!
![image](https://github.com/Albeoris/Memoria/assets/9964576/3a21bc51-1c10-4de2-ba4c-2a27d1ae5c2d)
https://github.com/Albeoris/Memoria/assets/9964576/4f976481-916f-4316-9079-6d16d32e63fa
https://github.com/Albeoris/Memoria/assets/9964576/66a126be-28d4-4f0f-a247-8c87cbc4e239

This fixes so many problems, just changing that!

**Comment by snouz** [comment]
It also works with smoke or other effects!
![2024-06-09 14_47_55-FINAL FANTASY IX - Map_ 605 (L  Castle_Serpent’s G ) _ Index_Counter_ 45_3700 _ ](https://github.com/Albeoris/Memoria/assets/9964576/66478929-8f2d-45bb-9b94-d0a60d9ae8ae) without
![2024-06-09 14_49_08-FINAL FANTASY IX - Map_ 605 (L  Castle_Serpent’s G ) _ Index_Counter_ 45_3700 _ ](https://github.com/Albeoris/Memoria/assets/9964576/ff59a4d5-28c0-4a77-a325-67e77d590ede) with
