### ISSUE TITLE
Problem of controlling the character with the mouse.

### ISSUE THREAD

**Issue by Neografic** [Albeoris/Memoria#416]
Hello. I have a problem controlling the character with the mouse.  I'll try to explain it.

When I approach the character, a bubble with a dialog appears, left-clicking mouse button starts the dialog, but after that, when I want to move away from the character, and click on the cursor on the ground (left-clicking mouse), the character cannot move away and continues to launch a dialogue from the bubble (again). Disabling the display of dialog bubbles in the launcher does not help. It only helps if I use the keyboard controls (wsad) to move away from the character, but this is not very convenient. Please help me, how can I fix this?

**Comment by Neografic** [comment]
![326476286-aa0333ec-22bd-4e94-a6d4-d8aa0bb306cf](https://github.com/Albeoris/Memoria/assets/42569437/e49be90f-1034-4cd9-bbe8-29ad7d9f2c7d)

**Comment by SamsamTS** [comment]
Playing with the mouse feels pretty bad in general. It's difficult just to move around. Entering and exiting building is extremely difficult in some location. And there is this behavior/bug you just mentioned.

I recommend switching to a controller (more controllers are now supported since the last release) or keyboard.
