### ISSUE TITLE
Localization mods manager support

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#473]
Right now, these mods are not 1 click installable, but I don't really understand why, we have string replacement, memoria.ini overwrite, UI replacements...

**Comment by Tirlititi** [comment]
On top of the requirement of a direct and stable download link (which is something that is not provided by all the uploaders, for example NexusMods uses only [auto-generated temporary download links](https://app.swaggerhub.com/apis-docs/NexusMods/nexus-mods_public_api_params_in_form_data/1.0) and ask for programs like ours to use their [complicate API](https://github.com/Nexus-Mods/sso-integration-demo)), all the translation mods available now use the option ``[Import]`` instead of using mod folders. So we would either need to have these mods in a "mod folder" format or handle mods with the method ``[Import]``, or possibly make it so the files in these mods are properly handled in mod folders, I don't know...

**Comment by snouz** [comment]
@Tirlititi isn't that a closable one since your latest commit?

**Comment by Tirlititi** [comment]
Hopefully soon.
The mods still need to be converted (and possibly uploaded somewhere the Mod Manager can retrieve them). I'll be able to do it but I need to ask the different authors about it. I'll do that after the release.

**Comment by faospark** [comment]
I built a template mod to introduce translators on how to do bundle their existing mods to be compatible to be compatible to memoria .  im helping dkpsycho for his Brazilian Portuguese language  pack.  Tir's new export of .mes files would be great help
