### ISSUE TITLE
is there a way to completely disable Smooth Camera?

### ISSUE THREAD

**Issue by 2eronia** [Albeoris/Memoria#482]
this game could be ever played on a ultrawide monitor (21:9 or 32:9), like this issue:
https://github.com/Albeoris/Memoria/issues/197

but after applying the latest patch, I reckon that it should be the "Smooth Camera" feature which causes the 3D models offset alot, then this game is unplayable on a monitor wider than 16:9.
 : (

**Comment by snouz** [comment]
Hi 2eronia, the launcher contains a setting, that if you put at 0, completely removes camera smoothing.
![image](https://github.com/Albeoris/Memoria/assets/9964576/faab9ad6-8db8-425b-b948-9fd7ae1bad21)

I did not test with wider resolutions, since widescreen is supposed to be disabled if you select something other than 16:9 or 16:10. I'm very interested to know how you manage to activate it anyway?

**Comment by snouz** [comment]
This is very hacky, and not actually supported yet. I have changed some things related to widescreen indeed, but I intend to work on an actual UW feature in the future (I tried at one point to make the resolution purely dynamic, but I put it aside because that branch was starting to be quite unstable)

Still, it has nothing to do with the stabilization feature. But thanks for the detailed report!

**Comment by 2eronia** [comment]
> @2eronia Ultrawide feature is in the next version : )

HATs OFF.
Thanks alot for your great work!~
