### ISSUE TITLE
Blank, Cinna, and Marcus playable with maybe tweaks?

### ISSUE THREAD

**Issue by uzoko1** [Albeoris/Memoria#5]
I would love since Beatrix became a thing on the Memoria mod, that the Tantalus Troupe could also be factored in, by tweaks...maybe setting their skills to either match Zidane or Steiners? That is only if you can, mainly would love to just be able to have them in the game please!

**Comment by uzoko1** [comment]
What does it mean when you self-assigned this issue? Does that mean you are working on it?

**Comment by Albeoris** [comment]
This means that I am responsible for this issue. (:

**Comment by uzoko1** [comment]
Oh, but not touched yet right?

**Comment by Albeoris** [comment]
**Three problems:**
1) You cannot just change a character's preset because some events in the game are changing it (for example, fighting on the stage with special effects instead of magic).
2) You cannot just change the preset itself because active abilities linked with the command menu. So, if you replace Zidane's ability "Escape" to "Meteor" in the battle will still remain "Escape" (inaccessible, because you can not learn it).
3) You cannot just replace one ability in the command menu to the other because abilities have to go in order, one by one. You can set only the first and the count.

I do not know what to do.
I should think.

**Comment by Albeoris** [comment]
Hm... Seems like I can rewrite some code and set use a collection of ability ids instead the range.

**Comment by uzoko1** [comment]
Thats awesome you gave me some feedback, but they should be rewritable because they were able to be changed in HW from Tirilititi and I have done it as well, I know how the scripting works in HW just not steam cuz there is no...launcher? Everything is possible though. Let me know what else you have thought of.

**Comment by Albeoris** [comment]
Done.

1) In Memoria.ini:
[Hacks]
Enabled=1
AllCharactersAvailable=3

2) In \StreamingAssets\Data\Characters:
Add abilities to the character's list, and edit command file.

3) In game: Alt+F2
