### ISSUE TITLE
excalibur II time limit?

### ISSUE THREAD

**Issue by helpm3plz** [Albeoris/Memoria#504]
where or how to use it? i cant see it in the launcher

**Comment by Tirlititi** [comment]
Indeed that option is not in the launcher (yet).
You need to open your file ``Memoria.ini`` which is in the game's directory. Open it with the Notepad or any other text editor and search for the following line:
```ini
ExcaliburIINoTimeLimit = 0
```
Write a ``1`` instead of the ``0`` there and save. Also make sure that the line ``Enabled`` right above is also set to ``1``.
