### ISSUE TITLE
Animation of the jump rope disconnected from girls hands

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#568]
I have no idea if this is easily improvable, since the jump rope is connected to 2 models. Right now, they seem to make the rope levitate like magicians.

https://github.com/Albeoris/Memoria/assets/9964576/e7321407-630c-462f-a336-e17762584a16

**Comment by DV666** [comment]
Seems this issue is present since the PSX version => https://youtu.be/d2qIcV0l2aM?si=yeIpHT7LmheeVvLc&t=245. (difficult to see with the video's quality but it looked like it was there).

Given the animation of the girls' hands and the rope, I think it's going to be complicated (the hands turn at a much greater angle than the rope handles)... i will try to take a look sometime.

**Comment by SamsamTS** [comment]
Looking at it in slow-mo (fieldTPS = 5) you can clearly see that the rope turn in the opposite direction (clockwise) than the girls hands (counter-clockwise). The way the girls hands turn would make the rope go the other way around. Their animation would need to be reversed.

**Comment by DV666** [comment]
Found it with @SamsamTS : the PNJ use the wrong animation, i will take care of that.

https://github.com/Albeoris/Memoria/assets/17729817/c3021515-9717-492a-8347-3817904007c5
