### ISSUE TITLE
Steiner magic sword: too long on the last frame

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#605]
https://youtu.be/ml0uNMz3CtY?t=2208

**Comment by snouz** [comment]
In UnfifiedBattleSequencer, in UpdateSFXWait(), in:
if (sfx.runningSFX.Count > 0)
{
        stopWait = false;
}

if I comment that stopwait, every magic ends at a reasonable time. I tried with vivi's magic, and steiner's sword flare, fire..., and he comes back to his place faster, it still seems to wait for the actual visible spell to finish.

**Comment by Tirlititi** [comment]
No, doing that would completly break ``WaitSFXDone``.
If you want to fix that, you need to change the corresponding ``.seq`` by using a fixed wait instead of ``WaitSFXDone`` in files like [that one](https://github.com/Albeoris/Memoria/blob/main/Memoria.Patcher/StreamingAssets/Data/SpecialEffects/ef212/PlayerSequence.seq). You still need to have a ``WaitSFXDone`` in the sequence except you can place it after (but still before ``ActivateReflect``).

**Comment by DV666** [comment]
Yeah, that's what I was saying on Discord because this `Fire_Sword` duration is quite strange unlike most SFXs.
I wonder if this wasn't even to the PSX version : if i am not mistaken, that `WaitSFXDone` didn't exist for player sequences on the vanilla version, right? Everything was `Wait` based?

I can take care of reviewing all the .seq files from the magic sword, it will be very quick to do imo and i will made a PR just for that.

**Comment by DV666** [comment]
Fixed with #606, you can merge it if you want.
