### ISSUE TITLE
Mod catalog checking different repos (listed in a file)

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#644]
Idea by @barkermn01 while discussing on Discord

"i have been wanting to do it for quite some time i just have not had chance so that the ModManager part of memoria, has a list of repositories and we run a public one, users can add others to this list, 

the repo's have a json array that allows people to pull request to add there mods. and then the mods can be a few ways of being setup. 

First: download/extract mode, so they just provide a path to the mod from an online server,
Second: GitHub repo url, and file name and memoria just downloads the release so developers just create a release and make sure the file is called a specific name E.G release.zip 
This means mod manager can just push to a repo create a release and boom Memoria knows to update it because the release date will have changed, 

The zip one they will have to submit pull requests to update the path to the newest zip for memoria to track if it needs to update it."

Example Repo.json
```
[
  {
    Name:"mod1"
    Description:"mod1/description.md"
    Images:[ "mod1/image1.png", "mod1/image2.png" ]
    Files: "https://someurl.com/mod_version.zip"
    Type: "download"
  },  
  {
    Type:"GitHub"
    Repository:"https://www.github.com/username/repo/"
  },
]
```

We could add other types, like GDrive / Mega ect...

This way other people like Tsunamods team can run their own repos and the application actually updates about mod's without us having to release everytime

(...) there should be a warning on the dialog to add a repo, make sure you trust this repo then it's at the user's discretion
"

**Comment by barkermn01** [comment]
Just going to add some more of the chat in here,

asked: `we break compatibility with all current users` 
response: well we don't because the main loading of mods still uses the memoria.ini file, they will be no more broken than they are now can't update automatically

asked: "we might open up to potentially malicious softwares from untrusted sources"
response: yes and there should be a warning on the dialog to add a repo, make sure you trust this repo then it's the users discission

asked "the only reason I wanted to do that was to cleanup the commit timeline, which is not a good reason" 
response: mod creators also don't have to wait for us to merge the pull request for a release for there mods to be included or updated in memoria which i think is a much bigger benefit, coz what if development on memoria slows down again like it did before i came in and brough alot of life back to it with Tsunamods 😄 
moders waiting 6 months for a release of memoria to update there mods is not good for modders and will put them off creating or releasing mods

Another note added was the memoria primary repo should be it's own GitHub repo still using PR's but we could open that repo up to be moderated by other moderators such as Moogles & Mods discord, and Qhimm moderators
