### ISSUE TITLE
Black screen on battles in latest patch

### ISSUE THREAD

**Issue by davesierra** [Albeoris/Memoria#674]
Hello, as the title says. Here is a video: [here](https://jumpshare.com/s/wNEwpK8W01MZdDL1QXTw)

Game is not crashing, I can still pause, it's just a black screen.

**Comment by snouz** [comment]
Hi, thanks for the report, could since in the video you do a continue, where are you in the game exactly?
Does it do the same thing when you load a game?

We're planning to do a patch today, but I can't reproduce this exact problem.

Do you use Alternate Fantasy or Trance Seek or the character pack? or any other mod?

**Comment by snouz** [comment]
Hi again @davesierra, I'm really interested in your answer as we're working on a patch and we don't have anyone else getting the same problem so far. Thanks in advance

**Comment by andrewreeman** [comment]
I also get the same problem. Black screen on battles launching. Music continues but it looks like the battle won't load (there's load sound effects from a battle or anything). 

Game isn't frozen because the pause button still works. 

![image](https://github.com/user-attachments/assets/a22acd3e-fdf5-4821-adb9-04b773485b51)

Mods are:
![image](https://github.com/user-attachments/assets/b9c94b01-e464-4e08-98e4-9b23ab6a0c4d)

I've just tried an early save from Forgotten Continent and that does work. All saves are moogle saves. 
This is the first time playing FF9 from steam so it could be that the base game is broken at Kuja's palace but I'd expect more hits on google if that was the case. Let me know if I can help provide more info

**Comment by andrewreeman** [comment]
I just tried installing the previous version: https://github.com/Albeoris/Memoria/releases/tag/v2024.06.09
and that works ok so I think it may be related to this latest version: https://github.com/Albeoris/Memoria/releases/tag/v2024.08.05

Also, my previous save on the forgotten continent did initially load battles with the latest version. But when I was fighting the Ark boss battle it started ok and the...sort of froze. I can't fully explain it. It may not be related to this black screen issue.

I'm happy to continue to try help test this issue

**Comment by Tirlititi** [comment]
Did you update Alternate Fantasy? You need to have the version 6.5 of the mod with the latest version of Memoria.
They got an update almost at the same time.

**Comment by andrewreeman** [comment]
Thanks @Tirlititi. Updating Alternative Fantasy seemed to fix it for me. :-) 

Really do love memoria by the way. It's brilliant. Thanks

**Comment by davesierra** [comment]
Sorry for the late reply. I followed the thread and can confirm that updating (uninstall and reinstall) Alternate Fantasy fixes the problem, my bad as I wasn't aware I had to update the mods also.

Thanks!
