### ISSUE TITLE
We need a way to easily install and update Memoria on Steam Deck

### ISSUE THREAD

**Issue by snouz** [Albeoris/Memoria#736]
This is the number one request everywhere.

**Comment by petete1** [comment]
Just use 'protontricks-launch Memoria.Patcher.exe' and select the FFIX prefix.

**Comment by PSDseven** [comment]
@snouz Can you help me with the memoria 9.0 update? I downloaded it and overwrote the one I had and the old mod manager still came up instead of the new one where I could uninstall the old one. Would you be open to a video call where I can show you my directory and get your help. I am really struggling and would love to get the new update and continue playing FFIX

**Comment by snouz** [comment]
> @snouz Can you help me with the memoria 9.0 update? I downloaded it and overwrote the one I had and the old mod manager still came up instead of the new one where I could uninstall the old one. Would you be open to a video call where I can show you my directory and get your help. I am really struggling and would love to get the new update and continue playing FFIX

I have no knowledge on SD and don't own one. I can't offer such involved support sorry.
This ticket is specifically about making the update process easier in the future.

**Comment by snouz** [comment]
@PSDseven thanks to dotAXiS, installing on steamDeck is now just one line in the konsole:

`bash -c "$(curl -sL https://gist.githubusercontent.com/dotaxis/1ad1c64baa7ad9c1dabcb255ea6257ae/raw/c83a7991f007fe504731de01e5e133f6e219d87b/memoria.sh)"`
