### ISSUE TITLE
Support for 640x360/640x400 resolutions

### ISSUE THREAD

**Issue by MattHorn25** [Albeoris/Memoria#791]
As far as I can tell the current lowest supported resolution for Memoria is 640x480, which I believe is also the lowest res for the original PC release. Trying to force a lower res through the OS makes the game throw an error on launch.

In the interest of a 'retro-ish' experience I'd love to see support added for 640x360 and 640x400 resolutions, which are widescreen and match the existing lowest horizontal res, but are also roughly midway in pixel size between the original game and a modern display. It would allow the game to be played with a 'moderately pixelated' look without having to use shader injection which would mess with clean font rendering etc.

Of personal interest to me is the 640x400 resolution, which is exactly half/quarter of the Steam Deck display res and looks _very_ good on the Steam Deck when using Nearest Neighbor scaling in games with a compatible art style that support it. I can provide example images if needed. Thanks!

**Comment by snouz** [comment]
Reducing the resolution is probably not the way to go. Also, I don't understand where 640x360 is coming from. Original is 320x224, rounded to the nearest 4:3 res, 320x240, and multiplied by two to get 640x480 (which is the size of the vanilla image in the remaster)

FakeEric told me he has a way to make a shader to turn everything low-res, and I want to release original res backgrounds. Since the latest Memoria release, you can set the pixels as "not blending", which gives this result:

![image](https://github.com/user-attachments/assets/55cb3710-cc88-4018-8960-615718cda144)

**Comment by MattHorn25** [comment]
Thanks for the note about removing pixel blending, that would definitely be very useful when playing with the original backgrounds.

As for 640x360, that's simply what the 16:9 resolution is for the 640 pixel width - i.e. if 640x480, the smallest current res, was cut down to widescreen that's what the dimensions would be. It's not related to the original game res, but I'd say that neither the 2016 release backgrounds nor the Moguri backgrounds really depend on an integer scale to look their best, and neither would be visually compromised by displaying them in 640x360/640x400.

If you feel the reduction is not feasible, then of course please disregard - the request is entirely for aesthetic reasons.

**Comment by snouz** [comment]
I'm gonna close this ticket and I don't think a low res than 640x480 is needed, but know that some things are coming about bringing back the original look (I want to make a full demake mod)
