### ISSUE TITLE
How to replace the language symbol on the title interface

### ISSUE THREAD

**Issue by imcloud** [Albeoris/Memoria#824]
![image](https://github.com/user-attachments/assets/5f88bd64-f7e0-4526-9ff6-8516b6fa0a64)

I'm developing a localization mod that replaces the Japanese text with Chinese, and now there's only one small flaw left

When we select Japanese, the bottom left corner will become "**JP**". 

What should I do if I want to change "**JP**" to other characters?

I browsed through all the textures and texts in the game and couldn't find it. 

Does anyone know how to modify it?

I know this is not a problem with Memoria, I'm just here to ask for help

**Comment by Tirlititi** [comment]
Hum... I'm afraid that's the language's symbol actually, as defined in ``Localization.txt``. If that's the case, it cannot be modified yet because the symbol is also used in many places for programming purposes (for example for the path of many assets like ``embeddedasset/text/jp/...``).

I'll check if I can split that into a separate entry.

**Comment by imcloud** [comment]
> 嗯……恐怕这实际上是语言的符号，如 中定义的那样`Localization.txt`。如果是这样的话，它还不能被修改，因为该符号也用于许多编程目的（例如，用于许多资产的路径`embeddedasset/text/jp/...`）。
> 
> 我将检查是否可以将其拆分为单独的条目。

OK. Thanks again for your help

**Comment by Tirlititi** [comment]
Added a commit for that: you will be able to change that symbol with an entry called "NameShort" in the ``Localization.txt``. By default, these short names are the same as the "Symbol" (so "US", "JP", "IT" etc...) but they can be changed to something different without messing with the internal engine.

Something like that:
```txt
NameShort,US,UK,ZH,ES,FR,GR,IT
```
