### ISSUE TITLE
Heat Status effect does not work

### ISSUE THREAD

**Issue by Bojankety** [Albeoris/Memoria#835]
I am currently doing the Excalibur 2 Perfect Game challenge and the Taharka boss fight in Ipsen's Castle has you use the Heat status effect in order to win the fight optimally, but the effect literally does nothing. I have a video but this post doesn't allow me to attach it since the file size limit is so small even though the clip I have is not even 60 seconds long. The effect can be applied like normal, but wears off after the enemies next turn. Its supposed to outright kill off the enemy entirely once Taharka uses any following action. Can this be fixed somehow?

**Comment by Tirlititi** [comment]
Yes, I need to fix that bug for the next release. The "Easy kill proof" hidden status (also called "Heavy" in some places, like on the FF wikia) that many bosses have to be immune to gravity damage, instant KO, Matra Magic etc... also immune against Heat and Freeze instant KO since the latest release. It only concerns a few enemies but Taharka is the most important of them.

Sorry about that, I'm afraid you'll have to deal with that boss without Heat.

**Comment by Bojankety** [comment]
I thought so. Thank you for letting me know. I knew something wasn't right.
But unfortunately I can't defeat the boss any other way since I'm following
the E2PG guide to the letter and I don't have the proper equipment to deal
enough damage to kill Taharka, so Heat is literally the only optimal way,
especially for time saving purposes. The guide has me selling most of my
equipment that isn't missable for gil. So I kinda have no choice but to
wait until your next patch. When do you hope to release the next update?
Just curious.

**Comment by Tirlititi** [comment]
Here it is:
[HeatBugFix.zip](https://github.com/user-attachments/files/16994781/HeatBugFix.zip)
It took me sooo long to have Flame Saber's heat proc to test it ^^'

In order to apply the fix, simply unzip the folder ``HeatBugFix`` inside the game's folder ``FINAL FANTASY IX``, then go to the Launcher's Mod Manager: it should appear in the list of mods installed and you just need to activate it.

Sorry again for the inconvenience.

Please keep that issue opened so I don't forget to fix it in Memoria and it is more easy for other people to find the topic.

**Comment by Bojankety** [comment]
Awesome.

I could kiss your face right now. Hahaha.

Thank you so much.

I will keep the thread open, let your request so others can find it.

**Comment by Bojankety** [comment]
Just tested mod. Installed and activated perfectly fine and showed in mod manager as intended, but once in game, this happens... Characters and boss glitch uncontrollably and game soft locks. ATBs do not charge either.

https://github.com/user-attachments/assets/38617753-85cb-45f7-a2a6-6c236daf6da6

**Comment by Bojankety** [comment]
installing now, ill let you know

**Comment by Bojankety** [comment]
It works perfectly now, but shows death animation like you and I mentioned earlier. Thanks again for helping me with this.

**Comment by Tirlititi** [comment]
The fix I added in the commit [0ec4013](https://github.com/Albeoris/Memoria/commit/0ec40134fb53ec83c9ca7501105f4b3f10f07a4b) also prevents the dying animation. Since that's the behaviour for non-bosses, I thought it was more important to have it consistant.
