### ISSUE TITLE
Grey bars on top/bottom in native resolution 640x480 (4:3) 

### ISSUE THREAD

**Issue by Samaleus** [Albeoris/Memoria#858]
Despite the game being set to it's native resolution of 640x480 (4:3), there are grey bars on top and bottom. I'm using a connected crt monitor with  640x480 (4:3) native resolution. But, even when set to a window mode in any monitor, the game still displays the grey bars. I've played this game in the past without bars, so I know for a fact this has to be an issue caused by this extension or perhaps a game update. Any help would be highly appreciated, as I'm going crazy trying to fix it. Thanks in advance

**Comment by snouz** [comment]
This is actually not a bug.
The actual pixel resolution of the PSX game was 320x224, so not 4:3 but 4:2.8, but the PS1 stretched it vertically so you couldn't see it at the time. When the game was ported to PC/console, they chose to respect the actual resolution without the stretching. That means if you have a 4:3 window, these bars appear, but if you allow the window to be larger, the image will touch the top and bottom because it has space horizontally.

You can test, it's the same with the unmodded game. You can also measure with screenshots that it's not actual 4:3.

**Comment by snouz** [comment]
Also, you mention grey bars. The modded game has black bars, while the unmodded one has textured grey ones. So your game might not have Memoria installed at all.

**Comment by snouz** [comment]
![image](https://github.com/user-attachments/assets/b68d6c8b-e5b2-4e5d-a479-b55154015bc7)

![image](https://github.com/user-attachments/assets/328488f0-1fbf-437c-9635-c7fa81756cbb)

**Comment by Samaleus** [comment]
Yes, my bad. I just noticed this myself, all resolutions have bars indeed, regardless of mods. I do have, however, Memoria installed, shaders are working, etc. But the bars are still grey. I'm going to try Reshade to zoom in, I rather lose side screen and have no bars.

**Comment by canesalato** [comment]
Interestingly, I also see the grey bars. I have the latest memoria and Moguri 9.0
![Uploading PXL_20240925_174518766.jpg…]()

**Comment by Samaleus** [comment]
I've checked Memoria.ini for a setting that might replace the grey bars with black ones, couldn't find anything. So I guess it does it natively. But for some reason it's not working for us. Black would actually work great because the screen looks frameless like that, I wouldn't need to zoom in at all. What could be happening?

**Comment by canesalato** [comment]
Perhaps Memoria could add an option to zoom just enough to crop the bars out?
