### ISSUE TITLE
Softlock during Zorn & Thorn fight in Mt.Gulug

### ISSUE THREAD

**Issue by SamsamTS** [Albeoris/Memoria#890]
Reported by Tsuna:

> Not sure why, bbut I couldn't cast Terra Homing as Eiko in the forced Zorn, Thorn boss in Mt.Gulug.
> I got softlocked every time. Even with only Scavenger on which doesn't touch batt;e stuff.
> The opening fight dialog would run, but then they just stand there staring at each other.
> No UI, no control, nothing

https://www.twitch.tv/tsunamods/clip/EndearingObliviousPhoneCoolCat-YX5O7bio4CjE6yeL

**Comment by snouz** [comment]
He kept the memeoria.log?

**Comment by SamsamTS** [comment]
Sorry that was on stream (I wasn't watching at that time), I doubt he kept the log.

**Comment by SamsamTS** [comment]
Here's the [Memoria.log](https://github.com/user-attachments/files/17198639/Memoria.log)

Note that this is while using a new mod of his he was currently making, Scavenger mod, where he resets everyone's abilities at specific points of the game. It may well be what's causing the issue.

**Comment by SamsamTS** [comment]
It's seems to caused by this line @Tirlititi 
https://github.com/Albeoris/Memoria/blame/main/Assembly-CSharp/Global/btl_cmd.cs#L252

Tsuna is using a version compiled by Martin so this bug isn't the released version yet. Good thing he caught it.

**Comment by Tirlititi** [comment]
Oh...
That's because some of the unit's datas, in particular those that determines which abilities are available or not (with equipments, AP and Magic Sword), are not initialised until the menu gets enabled once, for some reason.
I'll fix the usage of Magic Sword there, but maybe we should consider initialising this kind of data much sooner in battles. I don't see why we wouldn't initialise that right after all the units are created, but maybe I'll delay that for a later release, in case there are other side-effects.
