### ISSUE TITLE
Tetra Master issue

### ISSUE THREAD

**Issue by Orycteropus** [Albeoris/Memoria#91]
Hi, 

Thanks for the work you've done. I dont know if this issue is related to the mod but according to the source files, I think it may be the case.

In fact, I dont understand the rules behind the Tetra Master with the mod installed. 

The rules should be as described in this post :
https://steamcommunity.com/sharedfiles/filedetails/?id=665845408

For example, for a card with 0P00, I should have a maximum attack of 15 and sometimes I have a lot more. 

Is their a way to retrieve the original system ?

**Comment by Albeoris** [comment]
Hi! It is very interesting. The fact is that in that version of the engine on the basis of which the mod was built, the minimum value was always 0, not N * 16. Thus, 0 means 0-16, and F means 0-255. o.o

I will try to find the time and check the latest version of the game. Perhaps this is a bug and card game has been patched, but I lost sight of it and did not update the mod.

Thanks for the information!

**Comment by Albeoris** [comment]
```csharp
atk= Random(0, atk);
def= Random(0, def);

if (atk >= def)
   victory 
else
  defeat 

```

This is how victory or defeat in a card battle is calculated **in the latest version of the game**.
The minimum is always 0. Thus, a card with 0 can defeat a card with F. Need to check how it worked in the PS1 version.

**Comment by Orycteropus** [comment]
Wow, the pc version has a really big problem with the tetra master then.

https://youtu.be/lFc4L_yHFEQ?t=1113

In this video you can see the behavior I encounter. Instead of decrementing the values soar when there is a fight. 

In the video below, you can see a behavior that seems to be more "normal".

https://youtu.be/cxO-l5MUbjs?t=1204

Thanks

**Comment by Albeoris** [comment]
Oh, it's all my fault. -_-
To fix this bug in the current version, you need to edit Memoria.ini as follows:

```
[TetraMaster]
ReduceRandom = 0
```

I will fix it now.

**How the original works (no need to multiply):**

1. Your card has an attack of 17.
2. My card has protection 2.
3. You take a number from 0 to 17 = 10.
4. I take a number from 0 to 2 = 0.
5. Attack (10) more defense (0), you won. An animation is playing, reducing your "HP" from 17 to 10, and my "HP" from 2 to 0.

**How ReduceRandom works:**

1. Your card has an attack of 17.
2. My card has protection 2.
3. You take a number from lowestAttack to 17.
4. I take a number from lowestDefense to 2.

**The problem is in this code:**
`csharp
Int32 lowestAttack = Math.Max ​​(0, battleCalculation.atkStart - (Int32) (MathEx.BitCount (attacker.arrow) * 1.5 - 1) << 4);`

**<< 4 is a multiplication by 16 using a bit shift:**
1 * 16 = 16
1 << 4 = 16

**But this is the least priority operation. Programmers do not know how to math. -_-**
2 - 1 * 16 = -14
2 - 1 << 4 = 16

**The logic should be as follows:**

1. The card has 3 arrows.
2. Truncate (3 * 1.5 - 1) << 4 = 3 * 16 = 48
3. The range of the random house is from 17 to 17-48, but not less than 0 = 0.

But due to a violation of the order of operations, we get `(7 - Truncate (3 * 1.5 - 1)) << 4 = 14 * 16 = 224`

**Comment by Orycteropus** [comment]
I just tested it, it works fine now. Thank you !
