### ISSUE TITLE
bug/glitch near Ramuh

### ISSUE THREAD

**Issue by ftaru17** [Albeoris/Memoria#939]
![image](https://github.com/user-attachments/assets/ff363327-3042-4a45-bad3-d444be13e8f8)

**Comment by Tirlititi** [comment]
This is because of mod incompatibilities.
You either use Alternate Fantasy or the Beatrix Mod. These re-enable a couple of dialogs that were suppressed during the game's development, including a couple of them for which the text in english was not translated or even don't exist (it is possible for texts to exist in a language and not in another one because they are different text blocks and sometimes they are even sorted differently).
And then, you use another mod that has higher priority in the list of your active mods. That other mod changes at least a couple of texts in Pinnacle Rocks but didn't add the suppressed dialogs back. Here you have what happens when the game is asked to display a dialog that doesn't exist. It may be that you previously encountered other dialogs that displayed simply "debug" for the same reason (I am pretty sure that Cleyra's ATE with the meeting between Freya, the High Priest and the King is in that situation).

**Comment by ftaru17** [comment]
neither Alternate Fantasy nor the Beatrix Mod. 
![image](https://github.com/user-attachments/assets/c5ceed4b-b008-4401-b83d-51398b591bc9)
although this is someone's manual translation into Russian (not from the Memoria catalog), so maybe...
"I am pretty sure that Cleyra's ATE with the meeting between Freya, the High Priest and the King is in that situation" - again no, everything is fine with the dialogues here

**Comment by Tirlititi** [comment]
Then your "HadesWorkshopMod" is based on Alternate Fantasy or the Beatrix Mod.
I mean, I know Zidane is not meant to walk to this exact spot and say something while turning his back to the others in vanilla. That's a part of the cutscene I coded myself. So whatever happens there, the script I added to my mods is involved, one way or the other.

Indeed, a translation mod also has this effects. It may be that the RGR team also translated a couple of dialogs that were not translated in english, which would explain why Cleyra's ATE works fine.
