### ISSUE TITLE
Card game controls not functioning when gamepad is connected

### ISSUE THREAD

**Issue by elliottmason** [Albeoris/Memoria#963]
I am using 2024.11.17 (was using the previous latest version). After selecting my deck, I can not move the cursor with the gamepad or the keyboard to select a card or a grid position. I noticed that if I don't connect a gamepad, launch the game, and start a card game, the controls seem to work with just the keyboard. However, if the gamepad is connected, the keyboard will not work with the card game regardless. I have tried toggling various settings related to controls, that didn't seem to make a difference. I am using a DualSense/PS5 controller connected via bluetooth.

**Comment by elliottmason** [comment]
I will say that the deadzone seems a bit sensitive for me, i.e. the resting position of the analog stick can sometimes cause my characters to continue walking when I want them to be still, and requires a slight correction. I know this can be a problem with bad controllers with drifting sticks, which I'm not sure applies to this controller or not.

Not totally sure, but it seems like the update made the analog controls slightly improved? For example, I can now control _how quickly_ my character walks with the analog stick, e.g. walk really slowly my gently pressing the analog stick, which I don't believe was possible previously. It feels more natural overall but also a bit sensitive imo.

I should have mentioned, this is a DualSense 5 controller in this case.

**Comment by Tirlititi** [comment]
You could already control the walking / running speed with the stick before, but it was more rough. If you find it too sensitive now, you can increase a bit the option "Advanced -> Analog controls -> Stick threshold" in the Launcher: that should fix your issue of the character continuing to walk when you want them to be still.

**Comment by SamsamTS** [comment]
> Not totally sure, but it seems like the update made the analog controls slightly improved? For example, I can now control _how quickly_ my character walks with the analog stick, e.g. walk really slowly by gently pushing the analog stick, which I don't believe was possible previously. It feels more natural overall, but also a bit sensitive imo.

Yes, that's something I worked on. Through the magic of emulation I was able to control both the PSX and Steam version at the same time with the same controller. I managed to get it pretty close (not exactly 1:1 but good enough).

And like Trilititi said there is an option for the threshold in case of stick drift. Before there was a 25% dead zone plus a fixed 10% threshold. Me removing the dead zone is what caused the issue so I restored it but is now it is circular and uses the threshold value instead of the fixed 25%. I might try to remove it again in the future but for now this will do.
