### ISSUE TITLE
Voice acting works differently for some npc in Lindblum

### ISSUE THREAD

**Issue by Algarad** [Albeoris/Memoria#977]
Hi all,

I noticed a different behavior with how voice acting works now. For example, the dialogue between the two guards in Lindblum in the screenshot works differently.

![391318529-ebe3cc09-aea3-493c-baa7-2ca1cc044690](https://github.com/user-attachments/assets/a0adf578-6e6c-42a4-946a-9b7d55a17700)

By reading memoria logs, I can see that now the game searches for _va_540_9_taken_0_, and not for _va_540_.
I assume that there is a new function for combined dialogues, something like an interaction within the dialogues between the two guards here.
I could not find anything about _multiplay-path_ or _taken(num)_ voice files in the Wiki about it.

    01.12.2024 10:19:00 |M| , path:Voices/IT/276/va_540_taken_0, multiplay-path:Voices/IT/276/va_540_9_taken_0 (not found)
    01.12.2024 10:19:01 |M| [VoiceActing] field:276, msg:541, text:Aureliano
    01.12.2024 10:19:01 |M| Si può entrare a piedi al castello
    01.12.2024 10:19:01 |M| sia da qui che dalla porta del drago
    01.12.2024 10:19:01 |M| terrestre che sta sotto la “nebbia”.

I also noticed that If I talk with the guard again and again, the VA file value increments and changes from _va_540_9_taken_0_ to _va_540_9_taken_1_ and so on.

    01.12.2024 10:19:09 |M| , path:Voices/IT/276/va_540_taken_1, multiplay-path:Voices/IT/276/va_540_9_taken_1 (not found)
    01.12.2024 10:19:10 |M| [VoiceActing] field:276, msg:541, text:Aureliano
    01.12.2024 10:19:10 |M| Si può entrare a piedi al castello
    01.12.2024 10:19:10 |M| sia da qui che dalla porta del drago
    01.12.2024 10:19:10 |M| terrestre che sta sotto la “nebbia”.

Thank you!

Algarad

**Comment by SamsamTS** [comment]
This is due to recent changes made for the festival of the Hunt. However it was done using the message ids which can be different in other languages. For instance 540 is for the message Zidane having or taking the lead in the US language but in your language it is for another message.

Worry not, I will make it so there's always the path without the `taken` or `held` as a fall back (in your case `Voices/IT/276/va_540`).

It would be nice to make the system work for all languages but there are 11 messages ids and 7 languages, so a total of 77 ids that need to manually be found, that's some tedious work.
